[package]
name = "rocrate-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
ro-crate-rs = "0.4"
tantivy = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
url = "2.5"
reqwest = { version = "0.12.24", features = ["json", "blocking"] }
